// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tktech_bdd.Migrations
{
    [DbContext(typeof(ProjetContext))]
    partial class ProjetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("tktech_bdd.Model.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TacheId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("PersonneId");

                    b.HasIndex("TacheId");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("tktech_bdd.Model.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Element");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tktech_bdd.Model.EnvoiNotif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotifId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NotifId");

                    b.HasIndex("PersonneId");

                    b.ToTable("EnvoisNotif");
                });

            modelBuilder.Entity("tktech_bdd.Model.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstProprio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoProfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("tktech_bdd.Model.Recurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("Recurrences");
                });

            modelBuilder.Entity("tktech_bdd.Model.Notif", b =>
                {
                    b.HasBaseType("tktech_bdd.Model.Element");

                    b.HasDiscriminator().HasValue("Notif");
                });

            modelBuilder.Entity("tktech_bdd.Model.Tache", b =>
                {
                    b.HasBaseType("tktech_bdd.Model.Element");

                    b.Property<bool>("EstFait")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Tache");
                });

            modelBuilder.Entity("tktech_bdd.Model.Association", b =>
                {
                    b.HasOne("tktech_bdd.Model.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tktech_bdd.Model.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tktech_bdd.Model.Tache", null)
                        .WithMany("ListeAssociations")
                        .HasForeignKey("TacheId");

                    b.Navigation("Element");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("tktech_bdd.Model.EnvoiNotif", b =>
                {
                    b.HasOne("tktech_bdd.Model.Notif", "Notif")
                        .WithMany("ListeDestinataires")
                        .HasForeignKey("NotifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tktech_bdd.Model.Personne", "Destinataire")
                        .WithMany()
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinataire");

                    b.Navigation("Notif");
                });

            modelBuilder.Entity("tktech_bdd.Model.Recurrence", b =>
                {
                    b.HasOne("tktech_bdd.Model.Element", "Element")
                        .WithMany("JoursRecurrence")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("tktech_bdd.Model.Element", b =>
                {
                    b.Navigation("JoursRecurrence");
                });

            modelBuilder.Entity("tktech_bdd.Model.Notif", b =>
                {
                    b.Navigation("ListeDestinataires");
                });

            modelBuilder.Entity("tktech_bdd.Model.Tache", b =>
                {
                    b.Navigation("ListeAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
